server:
  port: 8081

db:
  url: "jdbc:postgresql://localhost:5432/translations"
  username: "postgres"
  password: "postgres"

spring:
  application:
    name: app
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger.ui

client:
  microsoft:
    apikey: "9b25d96b62msh624a85ca76533bcp118dcdjsn1a08eab57f44"