server:
  port: 8081

db:
  username: "postgres"
  password: "postgres"
  url: "jdbc:postgresql://localhost:5432/translations"

spring:
  application:
    name: app
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

client:
  microsoft:
    apikey: "9b25d96b62msh624a85ca76533bcp118dcdjsn1a08eab57f44"